### ISSUE TITLE
web launched RunServer crashing

### ISSUE THREAD

**Issue by slwoodward** [hwoodward/Remote-Card-Games#108]
**Describe the bug**
Program crashes when game initiated from web page.

**To Reproduce**
Start a game using the web server.  Play for a while (this happened using the 0329 distribution executable).  A player's window will close.  In at least one instance the other players were unable to continue the game. 
Below is error report: cut/pasted from player's screen.

>runclient
pygame 1.9.5
Hello from the pygame community. https://www.pygame.org/contribute.html
Enter the host:port[woodstar.net:8080]
woodstar.net
8080
Enter the ruleset[HandAndFoot]
HandAndFoot
Select a display name: Ted
Connected to the server
Server disconnected
Traceback (most recent call last):
  File "RunClient.py", line 56, in <module>
  File "RunClient.py", line 43, in RunClient
  File "site-packages\PodSixNet\Connection.py", line 31, in Pump
  File "site-packages\PodSixNet\Connection.py", line 31, in <listcomp>
  File "client\Controller.py", line 216, in Network_disconnected
NameError: name 'exit' is not defined
[16376] Failed to execute script RunClient

**Comment by hwoodward** [comment]
I have confirmed that the pythonPath and the user identifier running the process (and thus permission levels) for the web launched instance match those running manually. I have also added logging so all the logging for the web instance is logged to a file that can be reviewed.
The plan is to reproduce the error and then review the logs for clues.

**Comment by slwoodward** [comment]
Haven't experienced this problem in months.
