### ISSUE TITLE
Add deck identifier to Card object so all cards in a game are unique

### ISSUE THREAD

**Issue by hwoodward** [hwoodward/Remote-Card-Games#112]
**What feature needs to be implemented**
Add deck id to Card base object and include it in the equality check. Make sure we use different deck ids in the decks combined to make draw piles. Ensure that any comparisons or rule checks still work.

**What is the priority to get done**
Not blocking any functionality, but would enable UI code simplification and probably fix the bug where sometimes a card you pick up from the pile is marked as prepared or the wrong wild card goes down.

**Where is the design for this feature documented**
Came up in review of Client UI refactor. Should be added to docs on Card Object when finished.

**Comment by slwoodward** [comment]
Implemented in AddDecktoCardDefinintion branch.  This branch is not backwards compatible with previous branches.
