### ISSUE TITLE
Hand information

### ISSUE THREAD

**Issue by slwoodward** [hwoodward/Remote-Card-Games#17]
All the players need to be able to see how many cards are in other players hands and feet.

The API between the server and UserInterfaces needs to include hand and foot counts. This could be done when sharing the visible card information.

**Comment by hwoodward** [comment]
I have a plan:
I'm going to put that information into the visible cards structure. However I have to figure out the format still

**Comment by hwoodward** [comment]
Figured out format - its now in the client API wiki. Not implemented obviously, but its designed and so I think it can be closed since we aren't starting to implement this part of the code right now.
