### ISSUE TITLE
Zaephod support

### ISSUE THREAD

**Issue by slwoodward** [hwoodward/Remote-Card-Games#18]
We need a way to end a turn when you go Zaephod (not out, but no cards left in hand).

On discard and play actions, the model should check if you're out of cards.
If you are Zaephod, then it should report an empty discard, and the turn ends.
The server should handle an empty discard appropriately.

**Comment by slwoodward** [comment]
10/5 update -- currently if you hit "discard" button in UI and you're Zaephod, then the program crashes.  However, there is currently no other way to end the turn.

**Comment by hwoodward** [comment]
So - most of the logic for this is in the clientState's discard method.
That method needs to 
* See if you have provided an empty discards lit
  * See if you have cards left
    * error if you do
  * if you don't have cards left check if you have gone out
    * if you have deal with that
    * if you haven't submit empty discard list to server (that should be legal)
* confirm number of discards matches the number in the rules
  * if not error
* if normal discard submit to server

**Comment by slwoodward** [comment]
Zaephod now supported in master (worked in game on 1/25).
