### ISSUE TITLE
Send displayNames with public info

### ISSUE THREAD

**Issue by slwoodward** [hwoodward/Remote-Card-Games#43]
**Is a part of the design not going to actually work? Please describe how and why.**
We need for the public info sent to the client to include player names (in turn order). This is both for the 
 
**Describe the solution you'd like**
I prefer this to be  sent with the card status.

**Comment by hwoodward** [comment]
So - we are going to put the player names into the public information broadcasts - but structure is not clear how we finally want to structure this. There is a lot of public information to track. I want to get this right and documented so I'm putting it here first to allow feedback.

Information included in each broadcast from the server, for each player:
-name
-visible card dict
-hand status information

Current plan is to broadcast this in components, so it would be a json object with 'visible cards' then the list of visible cards for all players (in turn order), then it would be the list of hand statuses in turn order as the next part of the json. 

The player name could be either a third list (in turn order), part of the hand_status list, or passed with the hand_status list in a tuple of some sort. The third list is easiest and most consistent.

**Comment by hwoodward** [comment]
Second component of this:
currently hand info is to be specified in the ruleset somehow as to what info is in what order. There isn't a clear way to do this so I'm thinking of hard coding it in the client state instead and documenting it in the wiki. Then for games that didn't have all info we could find a way to appropriately ignore the irrelevant data (such as a list of indexes to put None in and the UI not rendering None).

**Comment by hwoodward** [comment]
Merged with handInfo
