### ISSUE TITLE
discard logic -- make it more generic

### ISSUE THREAD

**Issue by slwoodward** [hwoodward/Remote-Card-Games#44]
**What won't the app do that you think it should? Please describe.**
A clear and concise description of what the goal is.
Current discard logic assumes 1 card discarded unless zaephod.  Good for Hand and Foot, but not all games.

**Describe the solution you'd like**
Let's move this to rules, so that there's a minimum and maximum number of cards discarded, based on conditions.  EG - for hand and foot :
maxDiscards = 1, 
minDiscards = 1 if len(currentHand) >0 , else minDiscards = 0.
Currently maxDiscards and minDiscards do not exist as variables, the conditional, and the limits are all hard-coded.
**Describe alternatives you've considered**

**Additional context**

**Comment by hwoodward** [comment]
So - after a request for comments from others we decided on the following behavior:

1. UI confirms discard selection without any rule checking
2. After confirmation the UI calls the controller's discard method
3. The controller confirms the turn phase and will in the future use the ruleset in the client state to enforce the rules and then perform the discard

1 and 2 are done in the turn_phase merge, as along with the turn phase checking. The ruleset is not currently checked by the client_state.
