### ISSUE TITLE
How to assign keys to wild cards

### ISSUE THREAD

**Issue by hwoodward** [hwoodward/Remote-Card-Games#58]

**Comment by hwoodward** [comment]
We worked this out once and didn't write it down. We are at the point we should work out the details.

What I remember from our discussion:
We pass in all the cards.
We automatically handle everything we can, including skipping invalid cards
We return to the UI the list of pairs of cards and their valid key options. 
The UI somehow does a popup/overlay to let the user pick which key and then retries preparing them with that key specified.

The format I am tentatively using for returning is a list of lists. The sublists are [card, [key_options, listed, out]]

**Comment by slwoodward** [comment]
Fastest way to code this would be to use note on screen (the one that already tells user what his phase of play is).
Example of notes:
"You've prepared 5 wild cards, use key (a, 4-9, 0 (for ten), j, q, k) to designate which set 1st of 5 should join "  << user types 4
"You've prepared 5 wild cards, use key (a, 4-9, 0 (for ten), j, q, k) to designate which set 2 of 5 should join (so far have selected: 4)"  <user types 7
"You've prepared 5 wild cards, use key (a, 4-9, 0 (for ten), j, q, k) to designate which set 3 of 5 should join (so far have selected: 4,7)" <user types a
etc...

**Comment by hwoodward** [comment]
I like the overall concept.

What does a mean?
Also, when you prepare a card the note is set to 'you have prepared these cards' then all their prepared cards, you would have to reset the note a lot. This would work better if you could see note history.
