### ISSUE TITLE
display large hands gracefully

### ISSUE THREAD

**Issue by slwoodward** [hwoodward/Remote-Card-Games#62]
If the player's hand gets too big not all the cards are visible.  Need a way for user to see all their cards.
We can either:
- scale the cards, so they get smaller, 
- start stacking them (similar to what happen on the table with played cards in real life).  
- considered having them scroll past or let user set some aside for future consideration ((similar to what happens in real life)  but both of these seem impractical and overly complex.

I'd like feedback on which people think is more desirable.

**Comment by hwoodward** [comment]
This may be worth putting out a request for comments in the whatsapp if you think you'll work on it in December.
I vote for 2 rows of cards, which I think is what you meant by stacking. That would lead to a lot of overlap areas where you could select more cards then intended, but I don't like the multi-select on overlap feature anyway.
