### ISSUE TITLE
picking up pile - corner case

### ISSUE THREAD

**Issue by slwoodward** [hwoodward/Remote-Card-Games#66]
When I tried to pick up the pile and meld simultaneously, the pile was picked up but the prepared cards were not played.  I had to hit play prepared cards button.   

I would have trouble reproducing the behavior, because I was working on something else at the time, and wasn't taking careful notes.
Suggest enhancement -- more instructions on picking up pile in notifications.  
EG: 
If you click on pile with nothing prepared, then message should be: "Prepare two cards of the same rank  (plus enough cards to meld if you haven't yet), then click on pile to pick up. "
AND 
if you do this then all the prepared cards should be played as if you had clicked on "play prepared cards" button.  << Since it's going to do the latter, I may wish to add confirmation of pick-up pile button.  "All prepared cards will be played, are you sure you want to pick up the pile?"

**Comment by hwoodward** [comment]
Is this still reproducible? I have never seen it myself.

**Comment by slwoodward** [comment]
Cannot reproduce, believe it was fixed when other fixes were implemented.
