### ISSUE TITLE
Wild card instructions.

### ISSUE THREAD

**Issue by slwoodward** [hwoodward/Remote-Card-Games#74]
When wild card prepared both handview and controller (I believe it comes the controller module)  set note (controller.notification).  Controller overwrites note from handview, but the handview note details how to designate wild cards in more detail. 

Either handview note should not be overwritten (controller note eliminated), or controller note should be more detailed and handview note should be eliminated.

**Comment by hwoodward** [comment]
I eliminated the controller note, but the notification of how you assigned your first wild card overrides the instructions for the second one.

**Comment by slwoodward** [comment]
We've fixed this.
