### ISSUE TITLE
UI design discussion

### ISSUE THREAD

**Issue by hwoodward** [hwoodward/Remote-Card-Games#78]
Ideas/options to improve the UI:
* Should we swap hand/foot indicator to be an image of a stacked foot instead of the current text?
* Any requests about table view display (current improvments are in issue #77 )
* Should we add a size indicator to the discard pile. Right now it just tells you if there aren't 8 in the 'you can't pick up' message if you try to pick up without preparing anything, adn if there are it says 'you don't have cards prepared'

**Comment by slwoodward** [comment]
I think this issue can be closed.
