### ISSUE TITLE
Installation/New Start Guide

### ISSUE THREAD

**Issue by hwoodward** [hwoodward/Remote-Card-Games#79]
**What feature needs to be implemented**
We need an easy way for people to get set up to play

**Where is the design for this feature documented**
Want an installation script and easy executables to launch the client that will prompt you for the server information and fill in commandline args.
Ideally you double click, tell it the server somehow (or maybe thats setup on install?) and then a commandline prompt pops up, you give your name, hit enter, and the pygame window opens.

**Additional context**
Everyone but Helen is on Windows, so only a windows process is necessary

**Comment by slwoodward** [comment]
Using pyinstaller and distributing the dist folder in a zip file.
