### ISSUE TITLE
UI Feedback from 2/6/2020 game

### ISSUE THREAD

**Issue by slwoodward** [hwoodward/Remote-Card-Games#87]
1. Need to display number of cards in discard pile.
2. Notes (especially instructions dealing with wild cards) need clean-up and clarification.  
    It would also be good to display what sets wilds belong to in a cleaner fashion.
3. Ready to Play button needs to be moved to lower right (where it's less likely to be accidentally clicked).

Proposed solutions:
1. will display number somewhere near discard pile, (possibly on top of it in special font color (?))
2. will remove note that lists prepared cards -- it rights over other notes that are useful.  I'm still considering how to display wilds designation.   May append text to notes (e.g. "(Wilds are prepared as:  AAKK4)").
3. is trivial.

**Comment by hwoodward** [comment]
Another thing for that list:
4. Ready to Play button needs to be more like a check box - needs to indicate if it is checked or not. I will be setting up a boolean for that in the controller.

**Comment by slwoodward** [comment]
Complete!
