### ISSUE TITLE
Ready button behavior

### ISSUE THREAD

**Issue by slwoodward** [hwoodward/Remote-Card-Games#90]
**Describe the bug**
The "ready" button deals a new hand each time you click it.  
**To Reproduce**
Click ready multiple times, you'll see different cards appear, and you'll get GAME OVER message on server.

**Expected behavior**
If actively playing then clicking on the button should not do anything.

Possible solution - could remove button entirely when it should be passive. However, it is not enough to stop drawing button (I tried that) because then clicking in that area still resulted in same behavior.  I think if I do a better job removing button (resetting it's rectangle to something without any area) then that solution may work.

**Comment by slwoodward** [comment]
Fixed in "incorporateGUIsuggestions" branch.

**Comment by slwoodward** [comment]
Work around in incorporateGUIsuggestions did not make area zero, instead it didn't respond to mouse clicks in that area when controller.ready TRUE. After discussion, changed criteria so that it doesn't draw buttons when server._state.round == -1.   This does not fix the underlying behavior causing the error, it merely hides it.

**Comment by hwoodward** [comment]
Found problem in code. I got rid of any detection to confirm if we are in the middle of a round on the server. I put a boolean in to track that and it should be resolved now - still needs testing.

**Comment by slwoodward** [comment]
GUI no longer displays button when playing  (functional fix) + underlying problem also fixed.
