### ISSUE TITLE
Should we allow players to join between rounds?

### ISSUE THREAD

**Issue by hwoodward** [hwoodward/Remote-Card-Games#91]
We currently don't allow anyone to connect after the start of the first round. However, with the addition of an in_round flag to the server we can allow joining between rounds without allowing it during a round itself.

I think it would be a nice feature to have. However it would require some thought to make sure that the server didn't hang at the end of the round on score reporting for the new player.

**Comment by slwoodward** [comment]
Implemented in  AddPlayerBetweenRounds  branch.
