### ISSUE TITLE
Server crashes when one player disconnects

### ISSUE THREAD

**Issue by hwoodward** [hwoodward/Remote-Card-Games#97]
**Describe the bug**
When one player (possibly the active player) disconnects, the server crashes.

Mostly seen when running with remote server, not yet reproduced locally.

**Comment by hwoodward** [comment]
Suspect - but have yet to confirm - that we are actually seeing the server crash when a player tries to connect during an active game, is denied, goes through disconnect code, and then we crash. The remote server has non=game pings happening on its ports at various times and thus may be more susceptible to this.

**Comment by hwoodward** [comment]
Confirmed that a player connecting during an active game crashed the server due to the disconnect code. Also confirmed that pinging the server port with a web browser had the same result. Both fixed in linked MR

**Comment by slwoodward** [comment]
Fixed and tested with group on March 28.
